## column Transformer

In [1]:
import pandas as pd
import numpy as np

In [5]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import LabelEncoder
from sklearn.impute import SimpleImputer

In [3]:
df=pd.read_csv('covid_toy.csv')
df

,age,gender,fever,cough,city,has_covid
0,60,Male,103.0,Mild,Kolkata,No
1,27,Male,100.0,Mild,Delhi,Yes
2,42,Male,101.0,Mild,Delhi,No
3,31,Female,98.0,Mild,Kolkata,No
4,65,Female,101.0,Mild,Mumbai,No
...,...,...,...,...,...,...
95,12,Female,104.0,Mild,Bangalore,No
96,51,Female,101.0,Strong,Kolkata,Yes
97,20,Female,101.0,Mild,Bangalore,No
98,5,Female,98.0,Strong,Mumbai,No


In [10]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [11]:
df['city'].value_counts()  #to get count of each category in column

city
Kolkata      32
Bangalore    30
Delhi        22
Mumbai       16
Name: count, dtype: int64

In [12]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df.drop(columns=['has_covid']),df['has_covid'],test_size=0.2)

In [13]:
X_train

,age,gender,fever,cough,city
56,71,Male,NaN,Strong,Kolkata
41,82,Male,NaN,Mild,Kolkata
40,49,Female,102.0,Mild,Delhi
14,51,Male,104.0,Mild,Bangalore
58,23,Male,98.0,Strong,Mumbai
...,...,...,...,...,...
73,34,Male,98.0,Strong,Kolkata
69,73,Female,103.0,Mild,Delhi
70,68,Female,101.0,Strong,Delhi
50,19,Male,101.0,Mild,Delhi


In [14]:
y_train

56     No
41    Yes
40     No
14     No
58    Yes
     ... 
73    Yes
69     No
70     No
50    Yes
75    Yes
Name: has_covid, Length: 80, dtype: object

In [16]:
X_test

,age,gender,fever,cough,city
17,40,Female,98.0,Strong,Delhi
39,50,Female,103.0,Mild,Kolkata
0,60,Male,103.0,Mild,Kolkata
38,49,Female,101.0,Mild,Delhi
90,59,Female,99.0,Strong,Delhi
78,11,Male,100.0,Mild,Bangalore
12,25,Female,99.0,Strong,Kolkata
89,46,Male,103.0,Strong,Bangalore
93,27,Male,100.0,Mild,Kolkata
80,14,Female,99.0,Mild,Mumbai


#### doing manualy

In [17]:
#imputer to fever colmn
si=SimpleImputer()
X_train_fever=si.fit_transform(X_train[['fever']])
X_test_fever=si.transform(X_test[['fever']])
X_train_fever  #missing value get replace by mean

array([[100.7],
       [100.7],
       [102. ],
       [104. ],
       [ 98. ],
       [100.7],
       [ 99. ],
       [101. ],
       [ 99. ],
       [100. ],
       [ 98. ],
       [100.7],
       [100. ],
       [100. ],
       [ 99. ],
       [100. ],
       [101. ],
       [102. ],
       [102. ],
       [101. ],
       [101. ],
       [102. ],
       [104. ],
       [103. ],
       [103. ],
       [104. ],
       [104. ],
       [ 98. ],
       [102. ],
       [100.7],
       [ 98. ],
       [101. ],
       [104. ],
       [100.7],
       [ 98. ],
       [102. ],
       [100. ],
       [102. ],
       [101. ],
       [100.7],
       [101. ],
       [101. ],
       [101. ],
       [100.7],
       [ 98. ],
       [ 98. ],
       [ 98. ],
       [100. ],
       [101. ],
       [ 99. ],
       [ 98. ],
       [104. ],
       [104. ],
       [100. ],
       [103. ],
       [ 98. ],
       [ 98. ],
       [100.7],
       [100. ],
       [104. ],
       [ 99. ],
       [ 99. ],
       [

In [19]:
#OrdinalEncoding on cough
oe=OrdinalEncoder(categories=[['Mild','Strong']])
X_train_cough=oe.fit_transform(X_train[['cough']])
X_test_cough=oe.transform(X_test[['cough']])
X_train_cough

array([[1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],

In [22]:
#onehotEncoding on gender and city
ohe=OneHotEncoder(drop='first',sparse_output=False)
X_train_gen_city=ohe.fit_transform(X_train[['gender','city']])
X_test_gen_city=ohe.transform(X_test[['gender','city']])
X_train_gen_city

array([[1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 0., 0., 0.],
       [1., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [1., 1., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 0., 0., 0.],


In [26]:
X_train_gen_city.shape



(80, 4)

In [25]:
X_train_cough.shape

(80, 1)

In [24]:
X_train_fever.shape

(80, 1)

In [28]:
# Extracting Age
X_train_age = X_train.drop(columns=['gender','fever','cough','city']).values

# also the test data
X_test_age = X_test.drop(columns=['gender','fever','cough','city']).values

X_train_age.shape

(80, 1)

In [30]:
X_train_transformed = np.concatenate((X_train_age,X_train_fever,X_train_gen_city,X_train_cough),axis=1)
# also the test data
X_test_transformed = np.concatenate((X_test_age,X_test_fever,X_test_gen_city,X_test_cough),axis=1)

X_train_transformed.shape

(80, 7)

## column transformer

In [31]:
from sklearn.compose import ColumnTransformer

In [33]:
transformer = ColumnTransformer(transformers=[
    ('tnf1',SimpleImputer(),['fever']),
    ('tnf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
    ('tnf3',OneHotEncoder(sparse_output=False,drop='first'),['gender','city'])
],remainder='passthrough')

In [34]:
transformer.fit_transform(X_train).shape

(80, 7)

In [ ]:
transformer.transform(X_test).shape